/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppAccountApprovalsRouteImport } from './routes/_app.account-approvals'
import { Route as AppApprovalWorkflowsRouteImport } from './routes/_app.approval-workflows'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppCashLedgerRouteImport } from './routes/_app.cash-ledger'
import { Route as AppCostingRouteImport } from './routes/_app.costing'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppFinishedGoodsRouteImport } from './routes/_app.finished-goods'
import { Route as AppLogisticsRouteImport } from './routes/_app.logistics'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppPermissionsRouteImport } from './routes/_app.permissions'
import { Route as AppProductionRouteImport } from './routes/_app.production'
import { Route as AppProductionRequestsRouteImport } from './routes/_app.production-requests'
import { Route as AppPurchaseOrdersRouteImport } from './routes/_app.purchase-orders'
import { Route as AppRawMaterialsRouteImport } from './routes/_app.raw-materials'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRoleManagementRouteImport } from './routes/_app.role-management'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppSalesReturnsRouteImport } from './routes/_app.sales-returns'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppCashLedgerIndexRouteImport } from './routes/_app.cash-ledger.index'
import { Route as AppCashLedgerDebtsRouteImport } from './routes/_app.cash-ledger.debts'
import { Route as AppCashLedgerLedgerRouteImport } from './routes/_app.cash-ledger.ledger'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountApprovalsRoute = AppAccountApprovalsRouteImport.update({
  id: '/account-approvals',
  path: '/account-approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalWorkflowsRoute = AppApprovalWorkflowsRouteImport.update({
  id: '/approval-workflows',
  path: '/approval-workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppCashLedgerRoute = AppCashLedgerRouteImport.update({
  id: '/cash-ledger',
  path: '/cash-ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppCostingRoute = AppCostingRouteImport.update({
  id: '/costing',
  path: '/costing',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppFinishedGoodsRoute = AppFinishedGoodsRouteImport.update({
  id: '/finished-goods',
  path: '/finished-goods',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsRoute = AppLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissionsRoute = AppPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRequestsRoute = AppProductionRequestsRouteImport.update({
  id: '/production-requests',
  path: '/production-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppRawMaterialsRoute = AppRawMaterialsRouteImport.update({
  id: '/raw-materials',
  path: '/raw-materials',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRoleManagementRoute = AppRoleManagementRouteImport.update({
  id: '/role-management',
  path: '/role-management',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesReturnsRoute = AppSalesReturnsRouteImport.update({
  id: '/sales-returns',
  path: '/sales-returns',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppCashLedgerIndexRoute = AppCashLedgerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCashLedgerRoute,
} as any)
const AppCashLedgerDebtsRoute = AppCashLedgerDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AppCashLedgerRoute,
} as any)
const AppCashLedgerLedgerRoute = AppCashLedgerLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppCashLedgerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account-approvals': typeof AppAccountApprovalsRoute
  '/approval-workflows': typeof AppApprovalWorkflowsRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/cash-ledger': typeof AppCashLedgerRouteWithChildren
  '/costing': typeof AppCostingRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRoute
  '/expenses': typeof AppExpensesRoute
  '/finance': typeof AppFinanceRoute
  '/finished-goods': typeof AppFinishedGoodsRoute
  '/logistics': typeof AppLogisticsRoute
  '/payroll': typeof AppPayrollRoute
  '/permissions': typeof AppPermissionsRoute
  '/production': typeof AppProductionRoute
  '/production-requests': typeof AppProductionRequestsRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/raw-materials': typeof AppRawMaterialsRoute
  '/reports': typeof AppReportsRoute
  '/role-management': typeof AppRoleManagementRoute
  '/sales': typeof AppSalesRoute
  '/sales-returns': typeof AppSalesReturnsRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/users': typeof AppUsersRoute
  '/cash-ledger/debts': typeof AppCashLedgerDebtsRoute
  '/cash-ledger/ledger': typeof AppCashLedgerLedgerRoute
  '/cash-ledger/': typeof AppCashLedgerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account-approvals': typeof AppAccountApprovalsRoute
  '/approval-workflows': typeof AppApprovalWorkflowsRoute
  '/approvals': typeof AppApprovalsRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/costing': typeof AppCostingRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRoute
  '/expenses': typeof AppExpensesRoute
  '/finance': typeof AppFinanceRoute
  '/finished-goods': typeof AppFinishedGoodsRoute
  '/logistics': typeof AppLogisticsRoute
  '/payroll': typeof AppPayrollRoute
  '/permissions': typeof AppPermissionsRoute
  '/production': typeof AppProductionRoute
  '/production-requests': typeof AppProductionRequestsRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/raw-materials': typeof AppRawMaterialsRoute
  '/reports': typeof AppReportsRoute
  '/role-management': typeof AppRoleManagementRoute
  '/sales': typeof AppSalesRoute
  '/sales-returns': typeof AppSalesReturnsRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/users': typeof AppUsersRoute
  '/cash-ledger/debts': typeof AppCashLedgerDebtsRoute
  '/cash-ledger/ledger': typeof AppCashLedgerLedgerRoute
  '/cash-ledger': typeof AppCashLedgerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_app/account-approvals': typeof AppAccountApprovalsRoute
  '/_app/approval-workflows': typeof AppApprovalWorkflowsRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/cash-ledger': typeof AppCashLedgerRouteWithChildren
  '/_app/costing': typeof AppCostingRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/finished-goods': typeof AppFinishedGoodsRoute
  '/_app/logistics': typeof AppLogisticsRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/permissions': typeof AppPermissionsRoute
  '/_app/production': typeof AppProductionRoute
  '/_app/production-requests': typeof AppProductionRequestsRoute
  '/_app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/_app/raw-materials': typeof AppRawMaterialsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/role-management': typeof AppRoleManagementRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/sales-returns': typeof AppSalesReturnsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/cash-ledger/debts': typeof AppCashLedgerDebtsRoute
  '/_app/cash-ledger/ledger': typeof AppCashLedgerLedgerRoute
  '/_app/cash-ledger/': typeof AppCashLedgerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/account-approvals'
    | '/approval-workflows'
    | '/approvals'
    | '/audit-logs'
    | '/cash-ledger'
    | '/costing'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/expenses'
    | '/finance'
    | '/finished-goods'
    | '/logistics'
    | '/payroll'
    | '/permissions'
    | '/production'
    | '/production-requests'
    | '/purchase-orders'
    | '/raw-materials'
    | '/reports'
    | '/role-management'
    | '/sales'
    | '/sales-returns'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/cash-ledger/debts'
    | '/cash-ledger/ledger'
    | '/cash-ledger/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/account-approvals'
    | '/approval-workflows'
    | '/approvals'
    | '/audit-logs'
    | '/costing'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/expenses'
    | '/finance'
    | '/finished-goods'
    | '/logistics'
    | '/payroll'
    | '/permissions'
    | '/production'
    | '/production-requests'
    | '/purchase-orders'
    | '/raw-materials'
    | '/reports'
    | '/role-management'
    | '/sales'
    | '/sales-returns'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/cash-ledger/debts'
    | '/cash-ledger/ledger'
    | '/cash-ledger'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/reset-password'
    | '/_app/account-approvals'
    | '/_app/approval-workflows'
    | '/_app/approvals'
    | '/_app/audit-logs'
    | '/_app/cash-ledger'
    | '/_app/costing'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/employees'
    | '/_app/expenses'
    | '/_app/finance'
    | '/_app/finished-goods'
    | '/_app/logistics'
    | '/_app/payroll'
    | '/_app/permissions'
    | '/_app/production'
    | '/_app/production-requests'
    | '/_app/purchase-orders'
    | '/_app/raw-materials'
    | '/_app/reports'
    | '/_app/role-management'
    | '/_app/sales'
    | '/_app/sales-returns'
    | '/_app/settings'
    | '/_app/suppliers'
    | '/_app/users'
    | '/_app/cash-ledger/debts'
    | '/_app/cash-ledger/ledger'
    | '/_app/cash-ledger/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account-approvals': {
      id: '/_app/account-approvals'
      path: '/account-approvals'
      fullPath: '/account-approvals'
      preLoaderRoute: typeof AppAccountApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approval-workflows': {
      id: '/_app/approval-workflows'
      path: '/approval-workflows'
      fullPath: '/approval-workflows'
      preLoaderRoute: typeof AppApprovalWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-ledger': {
      id: '/_app/cash-ledger'
      path: '/cash-ledger'
      fullPath: '/cash-ledger'
      preLoaderRoute: typeof AppCashLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/costing': {
      id: '/_app/costing'
      path: '/costing'
      fullPath: '/costing'
      preLoaderRoute: typeof AppCostingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finished-goods': {
      id: '/_app/finished-goods'
      path: '/finished-goods'
      fullPath: '/finished-goods'
      preLoaderRoute: typeof AppFinishedGoodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logistics': {
      id: '/_app/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof AppLogisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permissions': {
      id: '/_app/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AppPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production': {
      id: '/_app/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production-requests': {
      id: '/_app/production-requests'
      path: '/production-requests'
      fullPath: '/production-requests'
      preLoaderRoute: typeof AppProductionRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders': {
      id: '/_app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/raw-materials': {
      id: '/_app/raw-materials'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof AppRawMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/role-management': {
      id: '/_app/role-management'
      path: '/role-management'
      fullPath: '/role-management'
      preLoaderRoute: typeof AppRoleManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-returns': {
      id: '/_app/sales-returns'
      path: '/sales-returns'
      fullPath: '/sales-returns'
      preLoaderRoute: typeof AppSalesReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-ledger/': {
      id: '/_app/cash-ledger/'
      path: '/'
      fullPath: '/cash-ledger/'
      preLoaderRoute: typeof AppCashLedgerIndexRouteImport
      parentRoute: typeof AppCashLedgerRoute
    }
    '/_app/cash-ledger/debts': {
      id: '/_app/cash-ledger/debts'
      path: '/debts'
      fullPath: '/cash-ledger/debts'
      preLoaderRoute: typeof AppCashLedgerDebtsRouteImport
      parentRoute: typeof AppCashLedgerRoute
    }
    '/_app/cash-ledger/ledger': {
      id: '/_app/cash-ledger/ledger'
      path: '/ledger'
      fullPath: '/cash-ledger/ledger'
      preLoaderRoute: typeof AppCashLedgerLedgerRouteImport
      parentRoute: typeof AppCashLedgerRoute
    }
  }
}

interface AppCashLedgerRouteChildren {
  AppCashLedgerDebtsRoute: typeof AppCashLedgerDebtsRoute
  AppCashLedgerLedgerRoute: typeof AppCashLedgerLedgerRoute
  AppCashLedgerIndexRoute: typeof AppCashLedgerIndexRoute
}

const AppCashLedgerRouteChildren: AppCashLedgerRouteChildren = {
  AppCashLedgerDebtsRoute: AppCashLedgerDebtsRoute,
  AppCashLedgerLedgerRoute: AppCashLedgerLedgerRoute,
  AppCashLedgerIndexRoute: AppCashLedgerIndexRoute,
}

const AppCashLedgerRouteWithChildren = AppCashLedgerRoute._addFileChildren(
  AppCashLedgerRouteChildren,
)

interface AppRouteChildren {
  AppAccountApprovalsRoute: typeof AppAccountApprovalsRoute
  AppApprovalWorkflowsRoute: typeof AppApprovalWorkflowsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppCashLedgerRoute: typeof AppCashLedgerRouteWithChildren
  AppCostingRoute: typeof AppCostingRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppFinishedGoodsRoute: typeof AppFinishedGoodsRoute
  AppLogisticsRoute: typeof AppLogisticsRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPermissionsRoute: typeof AppPermissionsRoute
  AppProductionRoute: typeof AppProductionRoute
  AppProductionRequestsRoute: typeof AppProductionRequestsRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppRawMaterialsRoute: typeof AppRawMaterialsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRoleManagementRoute: typeof AppRoleManagementRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSalesReturnsRoute: typeof AppSalesReturnsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountApprovalsRoute: AppAccountApprovalsRoute,
  AppApprovalWorkflowsRoute: AppApprovalWorkflowsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppCashLedgerRoute: AppCashLedgerRouteWithChildren,
  AppCostingRoute: AppCostingRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppFinishedGoodsRoute: AppFinishedGoodsRoute,
  AppLogisticsRoute: AppLogisticsRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPermissionsRoute: AppPermissionsRoute,
  AppProductionRoute: AppProductionRoute,
  AppProductionRequestsRoute: AppProductionRequestsRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppRawMaterialsRoute: AppRawMaterialsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRoleManagementRoute: AppRoleManagementRoute,
  AppSalesRoute: AppSalesRoute,
  AppSalesReturnsRoute: AppSalesReturnsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
